version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - '5173:5173'
    command: sh -c "npm run dev --host"
    environment:
      - CHOKIDAR_USEPOLLING=true
